package com.example.encuesta.utilidades;

public class utilidades {

    public static final String TABLA_ENCUESTA="encuesta_emt";
    public static final String CREAR_TABLA_ENCUESTA="CREATE TABLE "+ TABLA_ENCUESTA +" (" +
            " encuesta_emt INTEGER PRIMARY KEY AUTOINCREMENT," +
            " departamento TEXT NOT NULL DEFAULT ''," +
            " sci TEXT NOT NULL DEFAULT ''," +
            " municipio TEXT NOT NULL DEFAULT ''," +
            " instituto TEXT DEFAULT ''," +
            " nombre TEXT NOT NULL DEFAULT ''," +
            " apellido_paterno TEXT NOT NULL DEFAULT ''," +
            " apellido_materno TEXT NOT NULL DEFAULT ''," +
            " apodo TEXT NOT NULL DEFAULT ''," +
            " genero INTEGER NOT NULL DEFAULT 0," +
            " `edad` INTEGER NOT NULL DEFAULT 0," +
            " fecha_nacimiento TEXT NOT NULL," +
            " numero_ci TEXT NOT NULL DEFAULT ''," +
            " numero_run TEXT NOT NULL DEFAULT ''," +
            " ci INTEGER NOT NULL DEFAULT 0," +
            " run INTEGER NOT NULL DEFAULT 0," +
            " certificado_nacimiento INTEGER NOT NULL DEFAULT 0," +
            " libreta_militar INTEGER NOT NULL DEFAULT 0," +
            " documento_otro INTEGER NOT NULL DEFAULT 0," +
            " documento_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " documento_ninguno INTEGER NOT NULL DEFAULT 0," +
            " telefono TEXT NOT NULL DEFAULT ''," +
            " celular TEXT NOT NULL DEFAULT ''," +
            " estado_civil INTEGER NOT NULL DEFAULT 0," +
            " hijos INTEGER NOT NULL DEFAULT 0," +
            " n_hijos INTEGER NOT NULL DEFAULT 0," +
            " tipo_vivienda INTEGER NOT NULL DEFAULT 0," +
            " direccion varchar(256) NOT NULL DEFAULT ''," +
            " tipo_vivienda_otro varchar(20) NOT NULL DEFAULT ''," +
            " alquiler_orden INTEGER NOT NULL DEFAULT 0," +
            " alquiler_porc INTEGER NOT NULL DEFAULT 0," +
            " alimentacion_orden INTEGER NOT NULL DEFAULT 0," +
            " alimentacion_porc INTEGER NOT NULL DEFAULT 0," +
            " estudios_orden INTEGER NOT NULL DEFAULT 0," +
            " estudios_porc INTEGER NOT NULL DEFAULT 0," +
            " vestimenta_orden INTEGER NOT NULL DEFAULT 0," +
            " vestimenta_porc INTEGER NOT NULL DEFAULT 0," +
            " servicios_basicos_orden INTEGER NOT NULL DEFAULT 0," +
            " servicios_basicos_porc INTEGER NOT NULL DEFAULT 0," +
            " viajes_orden INTEGER NOT NULL DEFAULT 0," +
            " viajes_porc INTEGER NOT NULL DEFAULT 0," +
            " recreacion_orden INTEGER NOT NULL DEFAULT 0," +
            " recreacion_porc INTEGER NOT NULL DEFAULT 0," +
            " otro_orden INTEGER NOT NULL DEFAULT 0," +
            " otro_porc INTEGER NOT NULL DEFAULT 0," +
            " gasto_dinero_otro_especificar TEXT NOT NULL DEFAULT ''," +
            " gasto_dinero_no_sabe_orden INTEGER NOT NULL DEFAULT 0," +
            " gasto_dinero_no_sabe_porc INTEGER NOT NULL DEFAULT 0," +
            " enteraste_proyecto TEXT NOT NULL DEFAULT ''," +
            " lugar_vivienda INTEGER NOT NULL DEFAULT 0," +
            " lugar_vivienda_otro TEXT NOT NULL DEFAULT ''," +
            " tipo_lugar_vivienda INTEGER NOT NULL DEFAULT 0," +
            " tipo_lugar_vivienda_otro TEXT NOT NULL DEFAULT ''," +
            " cuartos_vivienda INTEGER NOT NULL DEFAULT 0," +
            " cuartos_dormir INTEGER NOT NULL DEFAULT 0," +
            " cuarto_solo INTEGER NOT NULL DEFAULT 0," +
            " servicio_sanitario INTEGER NOT NULL DEFAULT 0," +
            " posee_energia_electrica INTEGER NOT NULL DEFAULT 0," +
            " posee_energia_electrica_otro TEXT NOT NULL DEFAULT ''," +
            " agua INTEGER NOT NULL DEFAULT 0," +
            " otro_agua TEXT NOT NULL DEFAULT ''," +
            " energia INTEGER NOT NULL DEFAULT 0," +
            " gas_domiciliario INTEGER NOT NULL DEFAULT 0," +
            " gas_licuado INTEGER NOT NULL DEFAULT 0," +
            " carbon INTEGER NOT NULL DEFAULT 0," +
            " lena INTEGER NOT NULL DEFAULT 0," +
            " otro_combustible_nombre TEXT NOT NULL DEFAULT ''," +
            " otro_combustible INTEGER NOT NULL DEFAULT 0," +
            " pago_por_mi_cuenta INTEGER NOT NULL DEFAULT 0," +
            " comedores INTEGER NOT NULL DEFAULT 0," +
            " pagan_otros INTEGER NOT NULL DEFAULT 0," +
            " paga_familia INTEGER NOT NULL DEFAULT 0," +
            " regalan INTEGER NOT NULL DEFAULT 0," +
            " insumos INTEGER NOT NULL DEFAULT 0," +
            " otro_alimento INTEGER NOT NULL DEFAULT 0," +
            " otro_alimento_nombre INTEGER NOT NULL DEFAULT ''," +
            " comida_al_dia INTEGER NOT NULL DEFAULT 0," +
            " centro_salud_publica INTEGER NOT NULL DEFAULT 0," +
            " centro_salud_privado INTEGER NOT NULL DEFAULT 0," +
            " farmacia INTEGER NOT NULL DEFAULT 0," +
            " institucion INTEGER NOT NULL DEFAULT 0," +
            " naturista INTEGER NOT NULL DEFAULT 0," +
            " curo_solo INTEGER NOT NULL DEFAULT 0," +
            " otro_salud INTEGER NOT NULL DEFAULT 0," +
            " otro_salud_nombre TEXT NOT NULL DEFAULT ''," +
            " respuesta_salud_recien TEXT NOT NULL DEFAULT ''," +
            " dolor_cabeza INTEGER NOT NULL DEFAULT 0," +
            " dolor_cabeza_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " digestivas INTEGER NOT NULL DEFAULT 0," +
            " digestivas_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " respiratorias INTEGER NOT NULL DEFAULT 0," +
            " respiratorias_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " molestias_genitales INTEGER NOT NULL DEFAULT 0," +
            " molestias_genitales_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " cortes INTEGER NOT NULL DEFAULT 0," +
            " cortes_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " problemas_piel INTEGER NOT NULL DEFAULT 0," +
            " problemas_piel_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " fracturas INTEGER NOT NULL DEFAULT 0," +
            " fracturas_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " desmayos INTEGER NOT NULL DEFAULT 0," +
            " desmayos_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " its INTEGER NOT NULL DEFAULT 0," +
            " its_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " problema_salud_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " problema_salud_otro INTEGER NOT NULL DEFAULT 0," +
            " problema_salud_otro_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " alcohol INTEGER NOT NULL DEFAULT 0," +
            " alcohol_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " tabaco INTEGER NOT NULL DEFAULT 0," +
            " tabaco_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " tranquilizantes INTEGER NOT NULL DEFAULT 0," +
            " tranquilizantes_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " inhalantes INTEGER NOT NULL DEFAULT 0," +
            " inhalantes_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " marihuana INTEGER NOT NULL DEFAULT 0," +
            " marihuana_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " pasta_base INTEGER NOT NULL DEFAULT 0," +
            " pasta_base_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " cocaina INTEGER NOT NULL DEFAULT 0," +
            " cocaina_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " otro_substancia INTEGER NOT NULL DEFAULT 0," +
            " otro_substancia_frecuencia INTEGER NOT NULL DEFAULT 0," +
            " otro_substancia_nombre INTEGER DEFAULT ''," +
            " conoces_medio_anticonceptivo INTEGER NOT NULL DEFAULT 0," +
            " respuesta_metodo_anticonceptivo INTEGER NOT NULL DEFAULT ''," +
            " abstinencia INTEGER NOT NULL DEFAULT 0," +
            " ligadura_trompas INTEGER NOT NULL DEFAULT 0," +
            " vasectomia INTEGER NOT NULL DEFAULT 0," +
            " pildoras INTEGER NOT NULL DEFAULT 0," +
            " diu INTEGER NOT NULL DEFAULT 0," +
            " inyecciones INTEGER NOT NULL DEFAULT 0," +
            " implantes INTEGER NOT NULL DEFAULT 0," +
            " condon_masculino INTEGER NOT NULL DEFAULT 0," +
            " condon_femenino INTEGER NOT NULL DEFAULT 0," +
            " tabletas INTEGER NOT NULL DEFAULT 0," +
            " metodo_lactancia INTEGER NOT NULL DEFAULT 0," +
            " metodo_ritmo INTEGER NOT NULL DEFAULT 0," +
            " metodo_collar INTEGER NOT NULL DEFAULT 0," +
            " pildora_emergencia INTEGER NOT NULL DEFAULT 0," +
            " otro_anticonceptivo INTEGER NOT NULL DEFAULT 0," +
            " otro_anticonceptivo_nombre INTEGER NOT NULL DEFAULT ''," +
            " tuviste_enamorado INTEGER NOT NULL DEFAULT 0," +
            " relaciones_sexuales_recien INTEGER NOT NULL DEFAULT 0," +
            " edad_relacion_sexual TEXT NOT NULL DEFAULT ''," +
            " tuviste_relaciones_sexuales INTEGER NOT NULL DEFAULT 0," +
            " respuesta_decidir_relaciones TEXT NOT NULL DEFAULT ''," +
            " usar_anticonceptivo INTEGER NOT NULL DEFAULT 0," +
            " sin_proteccion INTEGER NOT NULL DEFAULT 0," +
            " negociar_relacion INTEGER NOT NULL DEFAULT 0," +
            " forzar_sin_proteccion INTEGER NOT NULL DEFAULT 0," +
            " otro_decidir_relacion INTEGER NOT NULL DEFAULT 0," +
            " otro_decidir_relacion_nombre INTEGER NOT NULL DEFAULT ''," +
            " usa_anticonceptivo_actualmente INTEGER NOT NULL DEFAULT 0," +
            " respuesta_no_anticonceptivo TEXT NOT NULL DEFAULT ''," +
            " costo_economico INTEGER NOT NULL DEFAULT 0," +
            " tener_hijo INTEGER NOT NULL DEFAULT 0," +
            " causan_dano_mujer INTEGER NOT NULL DEFAULT 0," +
            " condon_no_mismo INTEGER NOT NULL DEFAULT 0," +
            " noce_usar INTEGER NOT NULL DEFAULT 0," +
            " otro_no_anticonceptivo INTEGER NOT NULL DEFAULT 0," +
            " otro_no_anticonceptivo_nombre TEXT NOT NULL DEFAULT ''," +
            " desicion_uso_anticonceptivo INTEGER NOT NULL DEFAULT 0," +
            " embarazo INTEGER NOT NULL DEFAULT 0," +
            " desicion_embarazo INTEGER NOT NULL DEFAULT 0," +
            " otro_desicion_embarazo TEXT NOT NULL DEFAULT ''," +
            " edad_hijo TEXT NOT NULL DEFAULT ''," +
            " respuesta_situacion_violencia TEXT NOT NULL DEFAULT ''," +
            " situacion_violencia INTEGER NOT NULL DEFAULT 0," +
            " respuesta_prevenir_its TEXT NOT NULL DEFAULT ''," +
            " prevenir_its INTEGER NOT NULL DEFAULT 0," +
            " prevenir_its_otro text NOT NULL DEFAULT ''," +
            " embarazo_afecta_plan_vida INTEGER NOT NULL DEFAULT 0," +
            " vih_discriminacion INTEGER NOT NULL DEFAULT 0," +
            " detenido INTEGER NOT NULL DEFAULT 0," +
            " respuesta_causa_detenido TEXT NOT NULL DEFAULT ''," +
            " peleas INTEGER NOT NULL DEFAULT 0," +
            " robo INTEGER NOT NULL DEFAULT 0," +
            " hurto INTEGER NOT NULL DEFAULT 0," +
            " intencion_homicidio INTEGER NOT NULL DEFAULT 0," +
            " drogas INTEGER NOT NULL DEFAULT 0," +
            " otro_detenido INTEGER NOT NULL DEFAULT 0," +
            " otro_detenido_nombre TEXT NOT NULL DEFAULT ''," +
            " problema_ley INTEGER NOT NULL DEFAULT 0," +
            " fisica INTEGER NOT NULL DEFAULT 0," +
            " psicologica INTEGER NOT NULL DEFAULT 0," +
            " sexual INTEGER NOT NULL DEFAULT 0," +
            " otro_violencia INTEGER NOT NULL DEFAULT 0," +
            " otro_violencia_nombre TEXT NOT NULL DEFAULT ''," +
            " violencia_no_sabe INTEGER NOT NULL DEFAULT 0," +
            " padre_violencia INTEGER NOT NULL DEFAULT 0," +
            " madre_violencia INTEGER NOT NULL DEFAULT 0," +
            " hemanos_violencia INTEGER NOT NULL DEFAULT 0," +
            " parientes_violencia INTEGER NOT NULL DEFAULT 0," +
            " amigos_violencia INTEGER NOT NULL DEFAULT 0," +
            " pareja_violencia INTEGER NOT NULL DEFAULT 0," +
            " educadores_violencia INTEGER NOT NULL DEFAULT 0," +
            " profesores_violencia INTEGER NOT NULL DEFAULT 0," +
            " otro_sufrir_violencia INTEGER NOT NULL DEFAULT 0," +
            " otro_sufrir_violencia_nombre TEXT NOT NULL DEFAULT ''," +
            " acusaba_infiel INTEGER NOT NULL DEFAULT 0," +
            " celaba_amigo INTEGER NOT NULL DEFAULT 0," +
            " revisa_celular INTEGER NOT NULL DEFAULT 0," +
            " limitar_familia INTEGER NOT NULL DEFAULT 0," +
            " insulta_publico INTEGER NOT NULL DEFAULT 0," +
            " amenaza_abandono INTEGER NOT NULL DEFAULT 0," +
            " amenaza_hijos INTEGER NOT NULL DEFAULT 0," +
            " amenaza_economico INTEGER NOT NULL DEFAULT 0," +
            " rompe_objetos INTEGER NOT NULL DEFAULT 0," +
            " otro_violencia_pareja INTEGER NOT NULL DEFAULT 0," +
            " otro_violencia_pareja_nombre TEXT NOT NULL DEFAULT ''," +
            " empujado INTEGER NOT NULL DEFAULT 0," +
            " golpeado INTEGER NOT NULL DEFAULT 0," +
            " golpeado_objeto INTEGER NOT NULL DEFAULT 0," +
            " golpeado_marcas INTEGER NOT NULL DEFAULT 0," +
            " forzar_relaciones INTEGER NOT NULL DEFAULT 0," +
            " violencia_pareja_recientemente_otro INTEGER NOT NULL DEFAULT 0," +
            " violencia_pareja_recientemente_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " buscaste_ayuda INTEGER NOT NULL DEFAULT 0," +
            " donde_buscaste_ayuda TEXT NOT NULL DEFAULT ''," +
            " respuesta_no_buscar_ayuda TEXT NOT NULL DEFAULT ''," +
            " no_buscar_ayuda_miedo INTEGER NOT NULL DEFAULT 0," +
            " no_buscar_ayuda_creencias INTEGER NOT NULL DEFAULT 0," +
            " no_buscar_ayuda_represalias INTEGER NOT NULL DEFAULT 0," +
            " no_buscar_ayuda_otro INTEGER NOT NULL DEFAULT 0," +
            " no_buscar_ayuda_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " no_buscar_ayuda_nosabe INTEGER NOT NULL DEFAULT 0," +
            " conoces_organizacion TEXT NOT NULL DEFAULT ''," +
            " respuesta_sentir_mismo TEXT NOT NULL DEFAULT ''," +
            " me_acepto INTEGER NOT NULL DEFAULT 0," +
            " ser_otra_persona INTEGER NOT NULL DEFAULT 0," +
            " dependo_demas_dicen INTEGER NOT NULL DEFAULT 0," +
            " valiosa_unica INTEGER NOT NULL DEFAULT 0," +
            " personas_cualidades_limitaciones INTEGER NOT NULL DEFAULT 0," +
            " apoyo_sin_depender INTEGER NOT NULL DEFAULT 0," +
            " autonomia INTEGER NOT NULL DEFAULT 0," +
            " acepto_soy_siento INTEGER NOT NULL DEFAULT 0," +
            " responsable_actos INTEGER NOT NULL DEFAULT 0," +
            " otro_caracter INTEGER NOT NULL DEFAULT 0," +
            " otro_caracter_nombre TEXT NOT NULL DEFAULT ''," +
            " respuesta_tomar_desicion TEXT NOT NULL DEFAULT ''," +
            " amigos_familia_dicen INTEGER NOT NULL DEFAULT 0," +
            " busco_informacion INTEGER NOT NULL DEFAULT 0," +
            " actuo_impulsivamente INTEGER NOT NULL DEFAULT 0," +
            " reflexiono_actos INTEGER NOT NULL DEFAULT 0," +
            " opinion_personas_tema INTEGER DEFAULT 0," +
            " decido_solo INTEGER NOT NULL DEFAULT 0," +
            " otro_decision_importante INTEGER NOT NULL DEFAULT 0," +
            " otro_decision_importante_nombre TEXT NOT NULL DEFAULT ''," +
            " desarrollaste_plan_vida INTEGER NOT NULL DEFAULT 0," +
            " no_desarrollo_plan_vida TEXT NOT NULL DEFAULT ''," +
            " respuesta_pdp TEXT NOT NULL DEFAULT ''," +
            " planificar_estudia_trabajar INTEGER NOT NULL DEFAULT 0," +
            " metas_largo_plazo INTEGER NOT NULL DEFAULT 0," +
            " como_generar_ingresos INTEGER NOT NULL DEFAULT 0," +
            " otro_plan_vida INTEGER NOT NULL DEFAULT 0," +
            " otro_plan_vida_nombre TEXT NOT NULL DEFAULT ''," +
            " estudiante_actualmente INTEGER NOT NULL DEFAULT 0," +
            " colegio TEXT NOT NULL DEFAULT ''," +
            " nivel_colegio INTEGER NOT NULL DEFAULT 0," +
            " grado_colegio INTEGER NOT NULL DEFAULT 0," +
            " paralelo_colegio TEXT NOT NULL DEFAULT ''," +
            " nivel_secundaria INTEGER NOT NULL DEFAULT 0," +
            " grado_secundaria INTEGER NOT NULL DEFAULT 0," +
            " paralelo_secundaria TEXT NOT NULL DEFAULT ''," +
            " nivel_policia INTEGER NOT NULL DEFAULT 0," +
            " grado_policia INTEGER NOT NULL DEFAULT 0," +
            " nivel_universidad INTEGER NOT NULL DEFAULT 0," +
            " grado_universidad INTEGER NOT NULL DEFAULT 0," +
            " nivel_tecnico_universitario INTEGER NOT NULL DEFAULT 0," +
            " grado_tecnico_universitario INTEGER NOT NULL DEFAULT 0," +
            " nivel_tecnico_medio INTEGER NOT NULL DEFAULT 0," +
            " grado_tecnico_medio INTEGER NOT NULL DEFAULT 0," +
            " nivel_otro_actual INTEGER NOT NULL DEFAULT 0," +
            " nivel_no_sabe INTEGER NOT NULL DEFAULT 0," +
            " nivel_otro_actual_nombre TEXT NOT NULL DEFAULT ''," +
            " respuesta_motiva_estudiar TEXT NOT NULL DEFAULT ''," +
            " mejores_oportunidades_trabajo INTEGER NOT NULL DEFAULT 0," +
            " superacion_personal INTEGER NOT NULL DEFAULT 0," +
            " oportunidades_vida INTEGER NOT NULL DEFAULT 0," +
            " ingresos_economicos INTEGER NOT NULL DEFAULT 0," +
            " reconozcan_profesional INTEGER NOT NULL DEFAULT 0," +
            " otro_motiva_estudiar INTEGER NOT NULL DEFAULT 0," +
            " otro_motiva_estudiar_nombre TEXT NOT NULL DEFAULT ''," +
            " piensa_estudiar INTEGER NOT NULL DEFAULT 0," +
            " piensa_estudiar_otro TEXT NOT NULL DEFAULT ''," +
            " nivel_maximo INTEGER NOT NULL DEFAULT 0," +
            " grado_maximo INTEGER NOT NULL DEFAULT 0," +
            " paralelo_maximo TEXT NOT NULL DEFAULT ''," +
            " otro_nivel_maximo_nombre TEXT NOT NULL DEFAULT ''," +
            " respuesta_dejar_estudio TEXT NOT NULL DEFAULT ''," +
            " razon_dejar_estudiar INTEGER NOT NULL DEFAULT 0," +
            " volver_estudiar INTEGER NOT NULL DEFAULT 0," +
            " respuesta_agrupacion TEXT NOT NULL DEFAULT ''," +
            " ninguna_agrupacion INTEGER NOT NULL DEFAULT 0," +
            " agrupacion_vecinal INTEGER NOT NULL DEFAULT 0," +
            " agrupacion_jovenes INTEGER NOT NULL DEFAULT 0," +
            " gobierno_estudiantil INTEGER NOT NULL DEFAULT 0," +
            " otro_agrupacion INTEGER NOT NULL DEFAULT 0," +
            " otro_agrupacion_nombre TEXT NOT NULL DEFAULT ''," +
            " nombre_agrupacion TEXT NOT NULL DEFAULT ''," +
            " ocupaste_cargo_agrupacion INTEGER NOT NULL DEFAULT 0," +
            " respuesta_lider TEXT NOT NULL DEFAULT ''," +
            " mando_demas INTEGER NOT NULL DEFAULT 0," +
            " hago_tareas_demas INTEGER NOT NULL DEFAULT 0," +
            " confianza_desiciones INTEGER NOT NULL DEFAULT 0," +
            " justo_reparto_responsabilidad INTEGER NOT NULL DEFAULT 0," +
            " retroalimentacion_postivia INTEGER NOT NULL DEFAULT 0," +
            " otro_lider INTEGER NOT NULL DEFAULT 0," +
            " otro_lider_nombre TEXT NOT NULL DEFAULT ''," +
            " conoces_organizaciones_ayuda_jovenes INTEGER NOT NULL DEFAULT 0," +
            " conoces_organizaciones_ayuda_jovenes_nombre TEXT NOT NULL DEFAULT ''," +
            " conoces_organizaciones_ayuda_jovenes_objetivo TEXT NOT NULL DEFAULT ''," +
            " conoces_ley_342 INTEGER NOT NULL DEFAULT 0," +
            " conoces_consejo_juvenil INTEGER NOT NULL DEFAULT 0," +
            " conoces_actividad_consejo_juvenil INTEGER NOT NULL DEFAULT 0," +
            " participar_consejo_juvenil INTEGER NOT NULL DEFAULT 0," +
            " empleo INTEGER NOT NULL DEFAULT 0," +
            " emprendimiento INTEGER NOT NULL DEFAULT 0," +
            " proyecto_social INTEGER NOT NULL DEFAULT 0," +
            " estoy_realizando INTEGER NOT NULL DEFAULT 0," +
            " otro_actividad_ingreso INTEGER NOT NULL DEFAULT 0," +
            " otro_actividad_ingreso_nombre TEXT NOT NULL DEFAULT ''," +
            " opotunidad_realizar_emprendimiento INTEGER NOT NULL DEFAULT 0," +
            " menciona_tipo_emprendimiento TEXT NOT NULL DEFAULT ''," +
            " tiempo_estar_emprendimiento TEXT NOT NULL DEFAULT ''," +
            " contunia_emprendimiento INTEGER NOT NULL DEFAULT 0," +
            " no_continuo_emprendimiento TEXT NOT NULL DEFAULT ''," +
            " actividad_economica INTEGER NOT NULL DEFAULT 0," +
            " emprendimiento_plan_negocio INTEGER NOT NULL DEFAULT 0," +
            " productivo INTEGER NOT NULL DEFAULT 0," +
            " servicio INTEGER NOT NULL DEFAULT 0," +
            " otro_emprendimiento INTEGER NOT NULL DEFAULT 0," +
            " otro_emprendimiento_nombre TEXT NOT NULL DEFAULT ''," +
            " cual_emprendimiento TEXT NOT NULL DEFAULT ''," +
            " vendes_productos INTEGER NOT NULL DEFAULT 0," +
            " no_vendes_productos TEXT NOT NULL DEFAULT ''," +
            " respuesta_vendes_producto TEXT NOT NULL DEFAULT ''," +
            " ferias INTEGER NOT NULL DEFAULT 0," +
            " puestos INTEGER NOT NULL DEFAULT 0," +
            " mercado_formal INTEGER NOT NULL DEFAULT 0," +
            " consignacion INTEGER NOT NULL DEFAULT 0," +
            " particulares INTEGER NOT NULL DEFAULT 0," +
            " otro_lugar_vender INTEGER NOT NULL DEFAULT 0," +
            " otro_lugar_vender_nombre TEXT NOT NULL DEFAULT ''," +
            " frecuencia_vender INTEGER NOT NULL DEFAULT 0," +
            " frecuencia_vender_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " contratos INTEGER NOT NULL DEFAULT 0," +
            " acuerdos_verbales INTEGER NOT NULL DEFAULT 0," +
            " pedidos_verbales INTEGER NOT NULL DEFAULT 0," +
            " venta_atraves_otro INTEGER NOT NULL DEFAULT 0," +
            " venta_atraves_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " importante_vender_formal INTEGER NOT NULL DEFAULT 0," +
            " mes_1_monto INTEGER NOT NULL DEFAULT 0," +
            " mes_2_monto INTEGER NOT NULL DEFAULT 0," +
            " mes_3_monto INTEGER NOT NULL DEFAULT 0," +
            " mes_1_ingreso_dia INTEGER NOT NULL DEFAULT 0," +
            " mes_2_ingreso_dia INTEGER NOT NULL DEFAULT 0," +
            " mes_3_ingreso_dia INTEGER NOT NULL DEFAULT 0," +
            " mes_1_dias_trabajados TEXT NOT NULL DEFAULT ''," +
            " mes_2_dias_trabajados TEXT NOT NULL DEFAULT ''," +
            " mes_3_dias_trabajados TEXT NOT NULL DEFAULT ''," +
            " analizas_gastar INTEGER NOT NULL DEFAULT 0," +
            " realizas_analisis_costos INTEGER NOT NULL DEFAULT 0," +
            " respuesta_analisis TEXT NOT NULL DEFAULT ''," +
            " costo_directo INTEGER NOT NULL DEFAULT 0," +
            " costo_indirecto INTEGER NOT NULL DEFAULT 0," +
            " analisis_costos_otro INTEGER NOT NULL DEFAULT 0," +
            " analisis_costos_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " gastar_estudios_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_ropa_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_alimentacion_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_diversion_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_servicios_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_equipos_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_familia_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_ahorro_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_otro_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_otro_orden_nombre TEXT NOT NULL DEFAULT ''," +
            " alguna_vez_trabajaste INTEGER NOT NULL DEFAULT 0," +
            " respuesta_trabajaste TEXT NOT NULL DEFAULT ''," +
            " no_trabajo_estudios INTEGER NOT NULL DEFAULT 0," +
            " no_trabajo_edad INTEGER NOT NULL DEFAULT 0," +
            " no_trabajo_enfermedad INTEGER NOT NULL DEFAULT 0," +
            " no_trabajo_cuidado_familiar INTEGER NOT NULL DEFAULT 0," +
            " no_trabajo_encontrar INTEGER NOT NULL DEFAULT 0," +
            " no_trabajo_no_necesito INTEGER NOT NULL DEFAULT 0," +
            " no_trabajo_otro INTEGER NOT NULL DEFAULT 0," +
            " no_trabajo_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " gustaria_desarrollar_actividad INTEGER NOT NULL DEFAULT 0," +
            " si_gustaria_trabajar TEXT NOT NULL DEFAULT ''," +
            " no_gustaria_trabajar TEXT NOT NULL DEFAULT ''," +
            " realizate_capacitacion_trabajo INTEGER NOT NULL DEFAULT 0," +
            " respuesta_capacitacion TEXT NOT NULL DEFAULT ''," +
            " falta_recursos INTEGER NOT NULL DEFAULT 0," +
            " falta_tiempo INTEGER NOT NULL DEFAULT 0," +
            " falta_interes INTEGER NOT NULL DEFAULT 0," +
            " falta_capacitacion_otro INTEGER NOT NULL DEFAULT 0," +
            " falta_capacitacion_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " curso_realizo1 TEXT NOT NULL DEFAULT ''," +
            " curso_realizo2 TEXT NOT NULL DEFAULT ''," +
            " curso_realizo3 TEXT NOT NULL DEFAULT ''," +
            " te_gustaria_capacitarte INTEGER NOT NULL DEFAULT 0," +
            " rubro_desea_capacitar TEXT NOT NULL DEFAULT ''," +
            " no_desea_capacitarte TEXT NOT NULL DEFAULT ''," +
            " edad_trabajar TEXT NOT NULL DEFAULT ''," +
            " razon_edad_trabajar TEXT NOT NULL DEFAULT ''," +
            " trabajas_actualmente INTEGER NOT NULL DEFAULT 0," +
            " razon_no_trabajar TEXT NOT NULL DEFAULT ''," +
            " lugar_trabajo TEXT NOT NULL DEFAULT ''," +
            " cargo_trabajo TEXT NOT NULL DEFAULT ''," +
            " tiempo_trabajo INTEGER NOT NULL DEFAULT 0," +
            " encontrar_trabajo_familia INTEGER NOT NULL DEFAULT 0," +
            " encontrar_trabajo_amistad INTEGER NOT NULL DEFAULT 0," +
            " encontrar_trabajo_prensa INTEGER NOT NULL DEFAULT 0," +
            " encontrar_trabajo_agencia INTEGER NOT NULL DEFAULT 0," +
            " encontrar_trabajo_programa INTEGER NOT NULL DEFAULT 0," +
            " encontrar_trabajo_otro INTEGER NOT NULL DEFAULT 0," +
            " encontrar_trabajo_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " realizo_capacitacion INTEGER NOT NULL DEFAULT 0," +
            " razon_no_realizar_curso TEXT NOT NULL DEFAULT ''," +
            " capacitacion_colegio INTEGER NOT NULL DEFAULT 0," +
            " capacitacion_universidad INTEGER NOT NULL DEFAULT 0," +
            " capacitacion_instituto INTEGER NOT NULL DEFAULT 0," +
            " capacitacion_acogida INTEGER NOT NULL DEFAULT 0," +
            " capacitacion_cea INTEGER NOT NULL DEFAULT 0," +
            " capacitacion_icap INTEGER NOT NULL DEFAULT 0," +
            " capacitacion_fuente_laboral INTEGER NOT NULL DEFAULT 0," +
            " capacitacion_otro INTEGER NOT NULL DEFAULT 0," +
            " capacitacion_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " tiempo_capacitacion INTEGER NOT NULL DEFAULT 0," +
            " sirvio_capacitacion INTEGER NOT NULL DEFAULT 0," +
            " modalidad_contrato INTEGER NOT NULL DEFAULT 0," +
            " modalidad_contrato_otro TEXT NOT NULL DEFAULT ''," +
            " numero_trabajo INTEGER NOT NULL DEFAULT 0," +
            " trabajo_1 TEXT NOT NULL DEFAULT ''," +
            " trabajo_2 TEXT NOT NULL DEFAULT ''," +
            " horario_trabajo INTEGER NOT NULL DEFAULT 0," +
            " horario_trabajo_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " monto1 INTEGER NOT NULL DEFAULT 0," +
            " monto2 INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_estudio_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_ropa_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_alimentacion_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_diversion_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_servicios_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_equipo_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_familia_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_ahorro_orden INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_estudio_orden_otro INTEGER NOT NULL DEFAULT 0," +
            " gastar_dinero_estudio_orden_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " satisfecho_trabajo INTEGER NOT NULL DEFAULT 0," +
            " no_satisfecho TEXT NOT NULL DEFAULT ''," +
            " conoces_ley_laboral INTEGER NOT NULL DEFAULT 0," +
            " que_es_contrato INTEGER NOT NULL DEFAULT 0," +
            " cual_salario_minimo INTEGER NOT NULL DEFAULT 0," +
            " los_horarios INTEGER NOT NULL DEFAULT 0," +
            " derechos_deberes INTEGER NOT NULL DEFAULT 0," +
            " derecho_laboral_otro INTEGER NOT NULL DEFAULT 0," +
            " derecho_laboral_otro_nombre TEXT NOT NULL DEFAULT ''," +
            " conoces_bolsa_laboral INTEGER NOT NULL DEFAULT 0," +
            " mencionar_bolsa_laboral TEXT NOT NULL DEFAULT ''," +
            " conoces_plan_laboral INTEGER NOT NULL DEFAULT 0," +
            " ralizo_plan_laboral INTEGER NOT NULL DEFAULT 0," +
            " objetivo_plan_laboral TEXT NOT NULL DEFAULT ''," +
            " cumplir_plan_laboral INTEGER NOT NULL DEFAULT 0," +
            " programacion_recreativa INTEGER NOT NULL DEFAULT 0," +
            " programacion_recreativa_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " atencion_salud INTEGER NOT NULL DEFAULT 0," +
            " atencion_salud_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " atencion_albergues INTEGER NOT NULL DEFAULT 0," +
            " atencion_albergues_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " atencion_rehabilitacion INTEGER NOT NULL DEFAULT 0," +
            " atencion_rehabilitacion_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " participacion_juvenil INTEGER NOT NULL DEFAULT 0," +
            " participacion_juvenil_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " educacion INTEGER NOT NULL DEFAULT 0," +
            " educacion_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " empleo_juvenil INTEGER NOT NULL DEFAULT 0," +
            " empleo_juvenil_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " empoderamiento_personal INTEGER NOT NULL DEFAULT 0," +
            " empoderamiento_persona_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " negocio_juvenil INTEGER NOT NULL DEFAULT 0," +
            " negocio_juvenil_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " intervencion_defensoria INTEGER NOT NULL DEFAULT 0," +
            " intervencion_defensoria_satisfaccion INTEGER NOT NULL DEFAULT 0," +
            " ingreso_mensual_antes INTEGER NOT NULL DEFAULT 0," +
            " ingreso_mejoro INTEGER NOT NULL DEFAULT 0," +
            " trabajo_3_meses INTEGER NOT NULL DEFAULT 0," +
            " salario_antes INTEGER NOT NULL DEFAULT 0," +
            " ingreso_mensual_ahora INTEGER NOT NULL DEFAULT 0," +
            " programa_ayudo_empleo INTEGER NOT NULL DEFAULT 0," +
            " empleado_antes INTEGER NOT NULL DEFAULT 0," +
            " tiene_empleo_actual INTEGER NOT NULL DEFAULT 0," +
            " hubiera_tenido_plan_desarrollo_sin_programa INTEGER NOT NULL DEFAULT 0," +
            " mas_gusto_programa TEXT NOT NULL DEFAULT ''," +
            " comentarios TEXT NOT NULL DEFAULT ''," +
            " observacion_encuestado TEXT NOT NULL DEFAULT ''," +
            " fecha TEXT NOT NULL," +
            " id_usuario INTEGER NOT NULL" +
            ")";
}
